# Generated by Django 4.0.10 on 2023-12-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='isTeamMember',
            field=models.BooleanField(default=False),
        ),
    ]
