# Generated by Django 4.0.10 on 2023-12-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bloguser_matricnumber'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bloguser',
            managers=[
            ],
        ),
    ]
