# Generated by Django 4.0.10 on 2023-12-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_label_categorymodel_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='csc-421-blog/posts/cover-images')),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
            ],
        ),
    ]
